// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEW3mDQZwBsN-gc2s7IUQOGSZibc03_Bc',
    appId: '1:990306001889:web:12cde374e560a90bc3a8a0',
    messagingSenderId: '990306001889',
    projectId: 'test-app-7ec78',
    authDomain: 'test-app-7ec78.firebaseapp.com',
    storageBucket: 'test-app-7ec78.appspot.com',
    measurementId: 'G-4JH9GVT40R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8tTXUMYxGzYqZv6Rdy5BLFWxVlUvKfw',
    appId: '1:990306001889:android:641f4e7c2998d175c3a8a0',
    messagingSenderId: '990306001889',
    projectId: 'test-app-7ec78',
    storageBucket: 'test-app-7ec78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuH-9MiF0TmBKGU6UOkpNw4inBhxg6e1E',
    appId: '1:990306001889:ios:ac919a6baf8dcf87c3a8a0',
    messagingSenderId: '990306001889',
    projectId: 'test-app-7ec78',
    storageBucket: 'test-app-7ec78.appspot.com',
    androidClientId: '990306001889-jibm8e3renrd9oghiotjpcmprqj2k9et.apps.googleusercontent.com',
    iosClientId: '990306001889-kj0fp6grm9jsd1d06kpfvfpqo3otpnfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuH-9MiF0TmBKGU6UOkpNw4inBhxg6e1E',
    appId: '1:990306001889:ios:ac919a6baf8dcf87c3a8a0',
    messagingSenderId: '990306001889',
    projectId: 'test-app-7ec78',
    storageBucket: 'test-app-7ec78.appspot.com',
    androidClientId: '990306001889-jibm8e3renrd9oghiotjpcmprqj2k9et.apps.googleusercontent.com',
    iosClientId: '990306001889-kj0fp6grm9jsd1d06kpfvfpqo3otpnfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
